name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: |
          export REACT_APP_CONTAINERUP_BUILD=$(date -u +%Y%m%d%H%M%S)
          export REACT_APP_CONTAINERUP_COMMIT=${GITHUB_SHA::7}
          echo BUILD=${REACT_APP_CONTAINERUP_BUILD}
          echo COMMIT=${REACT_APP_CONTAINERUP_COMMIT}
          npm run build
