name: Build for release

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        description: The git ref to build
        type: string
      build_num:
        required: true
        description: The build number
        type: string
    outputs:
      COMMIT:
        description: "The commit hash of the build"
        value: ${{ jobs.build.outputs.COMMIT }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      COMMIT: ${{ steps.build.outputs.COMMIT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ContainerUp/containerup-web
          ref: ${{ inputs.git_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build project
        id: build
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          export REACT_APP_CONTAINERUP_VERSION=${GIT_REF}
          export REACT_APP_CONTAINERUP_BUILD=${BUILD_NUM}
          export REACT_APP_CONTAINERUP_COMMIT=${COMMIT}
          echo REACT_APP_CONTAINERUP_BUILD=${BUILD_NUM}
          echo REACT_APP_CONTAINERUP_COMMIT=${COMMIT}
          echo "COMMIT=${COMMIT}" >> ${GITHUB_OUTPUT}
          npm run build
        env:
          GIT_REF: ${{ inputs.git_ref }}
          BUILD_NUM: ${{ inputs.build_num }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/
