# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build for release

on:
  workflow_dispatch:
    inputs:
      git_ref:
        required: true
        description: The git ref to build
        type: string
      build_num:
        required: true
        description: The build number
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: |
          SHA=$(git rev-parse HEAD)
          export REACT_APP_CONTAINERUP_BUILD=${{ inputs.build_num }}
          export REACT_APP_CONTAINERUP_COMMIT=${SHA::7}
          echo BUILD=${REACT_APP_CONTAINERUP_BUILD}
          echo COMMIT=${REACT_APP_CONTAINERUP_COMMIT}
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/
